# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 541))
        self.tabWidget.setMaximumSize(QtCore.QSize(791, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.text_tab = QtWidgets.QWidget()
        self.text_tab.setObjectName("text_tab")
        self.tabWidget.addTab(self.text_tab, "")
        self.img_tab = QtWidgets.QWidget()
        self.img_tab.setObjectName("img_tab")
        self.tabWidget.addTab(self.img_tab, "")
        self.static_vid_tab = QtWidgets.QWidget()
        self.static_vid_tab.setObjectName("static_vid_tab")
        self.tabWidget.addTab(self.static_vid_tab, "")
        self.stream_vid_tab = QtWidgets.QWidget()
        self.stream_vid_tab.setObjectName("stream_vid_tab")
        self.tabWidget.addTab(self.stream_vid_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.text_tab), _translate("MainWindow", "指令"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.img_tab), _translate("MainWindow", "图片"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.static_vid_tab), _translate("MainWindow", "静态视频"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stream_vid_tab), _translate("MainWindow", "流式视频"))
